name: "Deploy my CloudFormation stack to staging"

on:
  push:
    branches:
      - "webIQGitSync.local" # only execute this workflow when I’m pushing to “staging”

env:
  AWS_ROLE: arn:aws:iam::715841359129:role/webIQGitSyncRole
  AWS_REGION: us-east-1


jobs:
  deploy:
    runs-on: ubuntu-latest
    # Permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      
        

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Run a one-line script
        run: aws cloudformation create-stack --stack-name iQn --template-body file://iQn.yaml --capabilities CAPABILITY_NAMED_IAM --region us-east-1 --profile AWSAdministratorAccess-715841359129
<<<<<<< HEAD

=======
>>>>>>> fe12f5696e1b118c92267eb77e1d6f206da54239

      # Deploy VPC
      - name: Deploys my VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.APP_NAME }}-vpc
          template: ./iQn.yaml
          no-fail-on-empty-changeset: "1"
         
